services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: valorant_app
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    networks:
      - valorant_network

  db:
    image: mysql:8.0
    container_name: valorant_db
    restart: always
    environment:
      MYSQL_DATABASE: valorant_admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - valorant_db_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - valorant_network

volumes:
  valorant_db_data:

networks:
  valorant_network:
    driver: bridge
